// Code generated by logcopter-gen; DO NOT EDIT.

package main

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.vm-system.internal.web.tools")
