// Code generated by logcopter-gen; DO NOT EDIT.

package vmmodules

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.vm-system.pkg.vmmodules")
